# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'IBearYou_V6' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for IBearYou_V6

  target 'IBearYou_V6Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end
